// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolPortalAPI.Data;

#nullable disable

namespace SchoolPortalAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221117025328_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("SchoolPortalAPI.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HouseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = "male",
                            HouseId = 1,
                            ImageUrl = "http://hp-api.herokuapp.com/images/harry.jpg,Gryffindor",
                            Name = "Harry Potter"
                        },
                        new
                        {
                            Id = 2,
                            Gender = "female",
                            HouseId = 1,
                            ImageUrl = "http://hp-api.herokuapp.com/images/hermione.jpeg,Gryffindor",
                            Name = "Hermione Granger"
                        },
                        new
                        {
                            Id = 3,
                            Gender = "male",
                            HouseId = 1,
                            ImageUrl = "http://hp-api.herokuapp.com/images/ron.jpg,Gryffindor",
                            Name = "Ron Weasley"
                        },
                        new
                        {
                            Id = 4,
                            Gender = "male",
                            HouseId = 4,
                            ImageUrl = "http://hp-api.herokuapp.com/images/draco.jpg,Slytherin",
                            Name = "Draco Malfoy"
                        },
                        new
                        {
                            Id = 5,
                            Gender = "female",
                            HouseId = 4,
                            ImageUrl = "http://hp-api.herokuapp.com/images/bellatrix.jpg,Slytherin",
                            Name = "Bellatrix Lestrange"
                        },
                        new
                        {
                            Id = 6,
                            Gender = "female",
                            HouseId = 3,
                            ImageUrl = "http://hp-api.herokuapp.com/images/cho.jpg,Ravenclaw",
                            Name = "Cho Chang"
                        },
                        new
                        {
                            Id = 7,
                            Gender = "female",
                            HouseId = 3,
                            ImageUrl = "http://hp-api.herokuapp.com/images/luna.jpg,Ravenclaw",
                            Name = "Luna Lovegood"
                        },
                        new
                        {
                            Id = 8,
                            Gender = "male",
                            HouseId = 2,
                            ImageUrl = "http://hp-api.herokuapp.com/images/cedric.png,Hufflepuff",
                            Name = "Cedric Diggory"
                        },
                        new
                        {
                            Id = 9,
                            Gender = "female",
                            HouseId = 2,
                            ImageUrl = "https://static.wikia.nocookie.net/harrypotter/images/c/c8/Nymphadora_Tonks_DH_promo_headshot_.jpg/revision/latest?cb=20161119222048,Hufflepuff",
                            Name = "Nymphadora Tonks"
                        });
                });

            modelBuilder.Entity("SchoolPortalAPI.Entities.Founder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Founders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = "male",
                            ImageUrl = "https://static.wikia.nocookie.net/harrypotter/images/3/31/Founders_gryffindor1.jpg/revision/latest?cb=20180611200439",
                            Name = "Godric Gryffindor",
                            Quote = "We'll teach all those with brave deeds to their name."
                        },
                        new
                        {
                            Id = 2,
                            Gender = "female",
                            ImageUrl = "https://static.wikia.nocookie.net/harrypotter/images/d/d7/Helga_Hufflepuff.jpg/revision/latest?cb=20140615154415",
                            Name = "Helga Hufflepuff",
                            Quote = "I'll teach the lot and treat them just the same."
                        },
                        new
                        {
                            Id = 3,
                            Gender = "female",
                            ImageUrl = "https://static.wikia.nocookie.net/harrypotter/images/f/fd/Rowena_Ravenclaw_at_WWHP.jpg/revision/latest?cb=20140615151812",
                            Name = "Rowena Ravenclaw",
                            Quote = "Wit beyond measure is man's greatest treasure."
                        },
                        new
                        {
                            Id = 4,
                            Gender = "male",
                            ImageUrl = "https://static.wikia.nocookie.net/harrypotter/images/8/86/Salazar_Slytherin_WWHP.jpg/revision/latest?cb=20140615154545",
                            Name = "Salazar Slytherin",
                            Quote = "We'll teach just those whose ancestry's purest."
                        });
                });

            modelBuilder.Entity("SchoolPortalAPI.Entities.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FounderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FounderId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FounderId = 1,
                            LogoUrl = "https://static.wikia.nocookie.net/harrypotter/images/9/98/Gryffindor.jpg/revision/latest?cb=20110503103732",
                            Motto = "You might belong in Gryffindor,\r\nWhere dwell the brave at heart,\r\nTheir daring, nerve and chivalry\r\nSet Gryffindors apart.",
                            Name = "Gryffindor",
                            Value = "bravery, daring, nerve, and chivalry"
                        },
                        new
                        {
                            Id = 2,
                            FounderId = 2,
                            LogoUrl = "https://static.wikia.nocookie.net/harrypotter/images/0/06/Hufflepuff_ClearBG.png/revision/latest?cb=20161020182518",
                            Motto = "You might belong in Hufflepuff\r\nWhere they are just and loyal\r\nThose patient Hufflepuffs are true\r\nAnd unafraid of toil",
                            Name = "Hufflepuff",
                            Value = "hard work, dedication, patience, loyalty, and fair play"
                        },
                        new
                        {
                            Id = 3,
                            FounderId = 3,
                            LogoUrl = "https://static.wikia.nocookie.net/harrypotter/images/7/71/Ravenclaw_ClearBG.png/revision/latest?cb=20161020182442",
                            Motto = "Or yet in wise old Ravenclaw\r\nIf you’ve a ready mind\r\nWhere those of wit and learning\r\nWill always find their kind",
                            Name = "Ravenclaw",
                            Value = "intelligence, knowledge, curiosity, creativity and wit"
                        },
                        new
                        {
                            Id = 4,
                            FounderId = 4,
                            LogoUrl = "https://static.wikia.nocookie.net/harrypotter/images/0/00/Slytherin_ClearBG.png/revision/latest?cb=20161020182557",
                            Motto = "Or perhaps in Slytherin\r\nYou’ll make your real friends\r\nThose cunning folk use any means\r\nTo achieve their ends",
                            Name = "Slytherin",
                            Value = "ambition, leadership, self-preservation, cunning and resourcefulness"
                        });
                });

            modelBuilder.Entity("SchoolPortalAPI.Entities.Character", b =>
                {
                    b.HasOne("SchoolPortalAPI.Entities.House", "House")
                        .WithMany("Characters")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("SchoolPortalAPI.Entities.House", b =>
                {
                    b.HasOne("SchoolPortalAPI.Entities.Founder", "Founder")
                        .WithMany()
                        .HasForeignKey("FounderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Founder");
                });

            modelBuilder.Entity("SchoolPortalAPI.Entities.House", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
